using System.Windows.Controls;

namespace ES_AIRAC_PCKGE
{
    public partial class FeaturesGrid : UserControl
    {
        public FeaturesGrid()
        {
            InitializeComponents();
        }

        private void InitializeComponents()
        {
            // This method is typically auto-generated by the XAML compiler
            // We're adding it manually as a temporary workaround
            System.Uri resourceLocater = new System.Uri("/ES_AIRAC_PCKGE;component/FeaturesGrid.xaml", System.UriKind.Relative);
            System.Windows.Application.LoadComponent(this, resourceLocater);
        }
    }
}